### ISSUE TITLE
Golang

### ISSUE THREAD

**Issue by aa-tan** [aa-tan/random_weighted#3]
Implementation of random weighted selection using Golang.

**Comment by volmedo** [comment]
I'd like to work on this issue :)

**Comment by volmedo** [comment]
I just saw there is a pending PR covering this issue. The code seems to be "controversial" though.

Please let me know if I should go on and open a new PR for this or you prefer waiting for the other PR's author to say something.

Thanks!

**Comment by volmedo** [comment]
Since it was easy enough and a nice exercise, I opened a new PR anyway. Please feel free to close it if you don't find it useful.

Happy hacktoberfest! 🎃👻

**Comment by aa-tan** [comment]
Sorry for the late reply, thanks for the contribution!
